ALTER TABLE wcf1_contest ADD trackbacks SMALLINT(5) NOT NULL DEFAULT 0;

DROP TABLE IF EXISTS wcf1_contest_trackback;
CREATE TABLE wcf1_contest_trackback (
	trackbackID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	entryID INT(10) NOT NULL,
	time INT(10) NOT NULL,
	url VARCHAR(255) NOT NULL,
	applicationName VARCHAR(255) NOT NULL DEFAULT '',
	title VARCHAR(255) NOT NULL DEFAULT '',
	excerpt VARCHAR(255) NOT NULL DEFAULT '',
	KEY (entryID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
